version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "nest-demo-stack"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
disable_rollback = false
parameter_overrides = "Environment=\"production\""
image_repositories = []

